server:
  port: ${NOMAD_PORT_http}
spring:
  application:
    name: u-service-app-2
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        format: YAML
      discovery:
        instanceId: ${spring.application.name}
        healthCheckPath: /my-health-check
        healthCheckInterval: 20s
