server:
  port: ${NOMAD_PORT_router}
spring:
  application:
    name: spring-gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        enabled: true
        format: key_value
      discovery:
        instanceId: ${spring.application.name}
        healthCheckPath: /health
        healthCheckInterval: 20s
    gateway:
      routes:
        - id: external_api_one
          uri: lb://u-service-app-1
          predicates:
          - Path:
              pattern=/external_api_one/**
        - id: external_api_two
          uri: lb://u-service-app-2
          predicates:
          - Path:
              pattern=/external_api_two/**
      discovery:
        locator:
          enabled: true
        enabled: true

endpoints:
  acurator:
    enabled:true
management:
  endpoints:
    web:
      exposure:
        include: "*"
