server:
  port: 8091
spring:
  application:
    name: u-service-hello-app
  cloud:
    consul:
      config:
        format: YAML
      discovery:
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        healthCheckPath: /my-health-check
        healthCheckInterval: 20s
